### ISSUE TITLE
Dual Boot on Windows to GO

### ISSUE THREAD

**Issue by ARLBR10** [pbatard/uefi-ntfs#40] opened 2023-11-28 20:41 UTC
Hello Guys! So i am trying to create a "Portable" device with Windows and Linux but now i am in trouble. I already did my Windows To Go  with Rufus But after Instaling Ubuntu Linux was needed to create a grub2 bootloader and i lost my files from the original Rufus UEFI_NTFS partition and now i can't boot Windows. Is stuck at "Please Wait" and don't boot and doesn't read something in the disk.

Things i Already did.
- In this repo you have releases of the UEFI NTFS and i already copy then but didn't work.
- In this repo you have a link to a release with the NTFS drivers and i already copy then and didn't work. 
- I created the boot manager with the original Windows Boot Manager and didn't work.

Some context 'When was booting inside the PC was working with the original Windows Boot Manager but after some tries the Windows reported some error in a BCD file and i can't fix so i go to the Rufus Original and now its just stuck. I don't want to rebuild my windows but if needed okay.'

**Comment by pbatard** [comment] 2023-11-28 20:45
> Is stuck at "Please Wait"

If that's the Windows' "Please Wait" then it means you have no need for UEFI:NTFS because it wouldn't boot at all otherwise. If UEFI:NTFS was actually needed, you wouldn't even get to the "Please Wait" message. Instead your system would not boot Windows at all.

So I'm afraid that fiddling with UEFI:NTFS won't help you here and your error is elsewhere (which isn't surprising since Windows really doesn't like dual boot).

**Comment by ARLBR10** [comment] 2023-11-28 20:47
I now. I created with the Windows Boot Manager some time ago him booted but with error. When was inside the PC worked but outside with a Sata to USB 3 i am stuck.

**Comment by BiatuAutMiahn** [comment] 2023-11-28 23:28
screenshot would give more context

**Comment by ARLBR10** [comment] 2023-11-28 23:33
> screenshot would give more context

Is only a manufactured logo and Please Wait. I’ve tried to use the original Windows Boot Manager instead but I got a error that the BCD is not recognized.

**Comment by BiatuAutMiahn** [comment] 2023-11-28 23:42
did you run `bcdboot.exe` against the boot and windows volumes? Seriously, a screenshot would show us exactly what the problem is.

**Comment by pbatard** [comment] 2023-12-31 19:42
I'm going to close this issue, as I don't see how it's related to stantard UEFI:NTFS usage.

**Closed by pbatard** 2023-12-31 19:42 UTC
